name: Deploy to Cloudflare Pages
on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    env:
      CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
      CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      
      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      
      - name: Install dependencies
        run: npm install
      
      - name: Build Astro site
        run: npm run build
        env:
          NODE_ENV: production
      
      - name: Deploy to Cloudflare Pages
        run: |
          echo "Deploying to Cloudflare Pages..."
          echo "Project name: chongo-mhbeid29a5vq"
          
          # Check if project exists, create if not
          if ! npx wrangler pages project list 2>/dev/null | grep -q "chongo-mhbeid29a5vq"; then
            echo "Creating new Cloudflare Pages project: chongo-mhbeid29a5vq"
            npx wrangler pages project create chongo-mhbeid29a5vq --production-branch=main
          else
            echo "Project chongo-mhbeid29a5vq already exists"
          fi
          
          # Deploy to Cloudflare Pages
          npx wrangler pages deploy dist --project-name=chongo-mhbeid29a5vq --commit-dirty=true
